<%@ Page Language="C#" AutoEventWireup="true" CodeFile="FIRST.ASPX.cs" Inherits="FIRST" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:Button ID="Button1" runat="server" Height="26px" OnClick="Button1_Click" Text="ClickHere" Width="71px" />
    
    </div>
        <p>
            &nbsp;</p>
    </form>
</body>
</html>
